files:
  - source: /metadata/android/en-US/**/*.txt
    translation: /metadata/android/%locale%/%original_file_name%
  - source: /metadata/android/en-US/**/*.png
    translation: /metadata/android/%locale%/%original_file_name%
  - source: /authpass/lib/l10n/app_en.arb
    translation: /authpass/lib/l10n/app_%two_letters_code%.arb
