files:
  - source: /metadata/android/en-US/**
    translation: /metadata/android/%locale%
  - source: /metadata/android/en-US/**/*.png
    translation: /metadata/android/%locale%
  - source: authpass/lib/l10n/app_en.arb
    translation: authpass/lib/l10n/app_%two_letters_code%.arb
