name: authpass
description: Password Manager with support for kdbx 2.x

version: 1.3.0+114

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  kdbx: ^0.2.0
  kdbx:
    path: ../deps/kdbx.dart
  simple_form_field_validator:
    git:
      url: https://github.com/hpoul/flutter_utils.git
      path: packages/simple_form_field_validator
      ref: 4c65f09005a1086525ebe2ae004eccdc2dd56fe1
  logging: '>=0.11.3+2 <1.0.0'
  logging_appenders: ^0.4.0
  file_picker: ^1.4.3+2
  json_annotation: ^3.0.1
  built_value: ^7.0.8
  simple_json_persistence: ^0.2.0
  provider: ^3.1.0
  http: ^0.12.0+4
  meta: '>=1.0.0 <2.0.0'
  clock: ^1.0.1
  intl: ^0.16.1
#  path: ^1.6.4
  isolate: ^2.0.2
#  clipboard_manager: ^0.0.4
  quiver: ">=2.0.0 <3.0.0"
  tuple: ^1.0.3
  flutter_async_utils:
    git:
      url: https://github.com/hpoul/flutter_async_utils.git
      ref: b452a5be869fb4f824a20e930cc1756eea6ca90e
  flutter_svg: ^0.16.0
  charcode: ^1.1.2
  #usage: ^3.4.1
  usage:
    git:
      url: https://github.com/hpoul/usage.git
      ref: custom-user-agent
  package_info: ^0.4.0+13
  device_info: ^0.4.1+4
  path_provider: ^1.5.1
  path_provider_macos: ^0.0.2+1
  analytics_event_gen:
    path: ../deps/analytics_events/analytics_event_gen
  autofill_service:
    path: ../deps/autofill_service

  flutter_colorpicker: ^0.2.6
  flutter_speed_dial: ^1.2.5

  biometric_storage: ^0.3.1
#  biometric_storage:
#    path: ../deps/biometric_storage
  uuid: ^2.0.4
  url_launcher: ^5.4.1
  font_awesome_flutter: ^8.5.0
  rxdart: ^0.23.1
  qr_flutter: ^3.2.0

  # WebDAV
  http_auth: ^0.2.9

  # google drive
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1

  # dropbox
  #oauth2: ^1.3.0
  oauth2:
    #path: /Users/herbert/dev/patches/oauth2
    git:
      url: https://github.com/authpass/oauth2.git
      ref: 508e542284733bbf0e0515d8ef0bbb5d39d47021

  # FDE
  file_chooser:
    git:
      url: https://github.com/hpoul/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: a73321baa3a0e7c16c66e9180211ae247e63f39c
#      ref: android-dummy-plugin
#      url: https://github.com/google/flutter-desktop-embedding.git
#      path: plugins/file_chooser
#  url_launcher_fde:
#    git:
#      url: https://github.com/hpoul/flutter-desktop-embedding.git
#      path: plugins/flutter_plugins/url_launcher_fde
#      ref: a73321baa3a0e7c16c66e9180211ae247e63f39c
#  path_provider_fde:
#    git:
#      url: https://github.com/hpoul/flutter-desktop-embedding.git
#      path: plugins/flutter_plugins/path_provider_fde
#      ref: a73321baa3a0e7c16c66e9180211ae247e63f39c

  macos_secure_bookmarks: ^0.1.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  build_runner: ^1.7.3
  builder_static_text: ^0.0.1+2
  built_value_generator: ^7.0.8
  pedantic: '>=1.7.0'
#
dependency_overrides:
  pedantic: ^1.9.0
#  url_launcher_fde:
#    path: /Users/herbert/dev/flutter/flutter-desktop-embedding/plugins/flutter_plugins/url_launcher_fde
#  file_chooser:
#    path: /Users/herbert/dev/flutter/flutter-desktop-embedding/plugins/file_chooser
#  biometric_storage
#    path: ../deps/biometric_storage
#  macos_secure_bookmarks:
#    path: /Users/herbert/dev/macos_secure_bookmarks


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
