name: build android samsungapps

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: ['samsungapps', 'sideload', 'huawei']

      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Postdeploy
      env:
        BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
      run: authpass/_tools/postdeploy.sh
    - name: debug android directory
      run: echo "${ANDROID_SDK_ROOT} , ${ANDROID_HOME}"
    - name: install ndk
#      run: 'yes | sdkmanager "ndk;21.0.6113669"'
      run: echo "y" | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
    - name: ci-install-deps
      run: "./authpass/_tools/ci-install-deps.sh android"
    - name: build ${{ matrix.flavor }} apk
      id: buildapk
      env:
        GIT_AUTHOR_NAME: 'Github Action CI'
        GIT_AUTHOR_EMAIL: 'herbert.github.ci@codeux.design'
        GIT_COMMITTER_NAME: 'Github Action CI'
        GIT_COMMITTER_EMAIL: 'herbert.github.ci@codeux.design'
      run: "./authpass/_tools/ci-release.sh android ${{ matrix.flavor }}"
    - uses: actions/upload-artifact@v1
      if: matrix.flavor != 'huawei'
      with:
        name: app-${{ matrix.flavor }}-release-${{steps.buildapk.outputs.appbuildnumber}}.apk
        path: authpass/build/app/outputs/apk/${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk
    - uses: actions/upload-artifact@v1
      if: matrix.flavor == 'huawei'
      with:
        name: app-${{ matrix.flavor }}-release-${{steps.buildapk.outputs.appbuildnumber}}.aab
        path: authpass/build/app/outputs/bundle/${{ matrix.flavor }}Release/app-${{ matrix.flavor }}-release.aab

