name: build android samsungapps

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Postdeploy
      env:
        BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
      run: authpass/_tools/postdeploy.sh
    - name: ci-install-deps
      run: "./authpass/_tools/ci-install-deps.sh android"
    - name: build samsungapps apk
      id: buildapk
      env:
        GIT_AUTHOR_NAME: 'Github Action CI'
        GIT_AUTHOR_EMAIL: 'herbert.github.ci@codeux.design'
        GIT_COMMITTER_NAME: 'Github Action CI'
        GIT_COMMITTER_EMAIL: 'herbert.github.ci@codeux.design'
      run: "./authpass/_tools/ci-release.sh android samsungapps"
    - uses: actions/upload-artifact@v1
      with:
        name: app-samsungapps-release-${{steps.buildapk.outputs.appbuildnumber}}.apk
        path: authpass/build/app/outputs/apk/samsungapps/release/app-samsungapps-release.apk

