name: make_deb

on:
  push:
    branches:
      - 'main'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd debian/opt/authpass
          wget https://authpass-data.codeux.design/data/artifacts/authpass-linux-latest.tar.gz
          tar -zxvf authpass-linux-latest.tar.gz authpass -C . --strip-components=1
          rm authpass-linux-latest.tar.gz
          version=$(cat version.txt)
          cd ../../../
          sed -i "s/1.0/${version}/g" debian/usr/share/applications/authpass.desktop
          sed -i "s/1.0/${version}/g" debian/DEBIAN/control
          dpkg-deb --build --root-owner-group ./debian 
          mv debian.deb authpass.deb
      - uses: actions/upload-artifact@v3
        with:
          name: authpass
          path: authpass.deb

#tar -zxvf authpass-linux-latest.tar.gz authpass/. -C .