name: unit test with coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: ci-install-deps
        run: "./authpass/_tools/ci-install-deps.sh android"
      - name: Postdeploy
        env:
          BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
        run: authpass/_tools/postdeploy.sh
      - run: authpass/_tools/test-coverage.sh

