name: github pages

on:
  push:
    branches:
      - stable
      - beta
      - web-beta

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Install
        run: |
          flutter config --enable-web
          pushd $FLUTTER_HOME/dev/tools && flutter pub get && popd
          pushd authpass && flutter pub get
      - name: Build
        run: cd authpass && flutter build web -t lib/env/web.dart

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./authpass/build/web
          allow_empty_commit: true

