name: build windows

on: 
  push:
    branches:
      - 'windows**'
      - 'stable'
      - 'beta'

jobs:
  build:

    strategy:
      matrix:
        flavor: ['windows']
        os: [windows-2019]
        vs: [2019]

      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: ci-install-deps
      shell: bash
      env:
        BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
      run: ./authpass/_tools/ci-install-deps.sh windows
    - name: build ${{ matrix.flavor }} apk
      id: buildapk
      shell: bash
      env:
        GIT_AUTHOR_NAME: 'Github Action CI'
        GIT_AUTHOR_EMAIL: 'herbert.github.ci@codeux.design'
        GIT_COMMITTER_NAME: 'Github Action CI'
        GIT_COMMITTER_EMAIL: 'herbert.github.ci@codeux.design'
      run: ./authpass/_tools/ci-release.sh ${{ matrix.flavor }}
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.buildapk.outputs.outputfilename }}
        path: authpass/${{ steps.buildapk.outputs.outputpath }}
    - name: upload artifact
      shell: bash
      run: ./authpass/_tools/upload-artifact.sh ${{ steps.buildapk.outputs.outputpath }}
    # - uses: snapcore/action-build@v1
    #   id: snapcraft
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: authpass-${{ steps.buildapk.outputs.appversion }}_${{ steps.buildapk.outputs.appbuildnumber }}-snap
    #     path: ${{ steps.snapcraft.outputs.snap }}
